apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 304165982753.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newName: 304165982753.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newTag: 8fa7af92
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
